import "./globals.css";
import { Inter } from "next/font/google";
import "./estiloglobal/sobre.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <nav style={{ backgroundColor: "blue", fontSize: "24px" }}>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/dashboard">Dashboard</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
